/**
 * The probe SDK is validated against the harness, not against itself.
 *
 * A conformance vector generated by the implementation it validates always
 * passes -- that is the failure mode that hides here. So there are no golden
 * files. The C library writes a bundle, and the TypeScript harness, written
 * independently to the same contract and knowing nothing about the C code,
 * verifies it, decodes it, and analyses it. If the two disagree about the
 * contract, this test is where it shows.
 *
 * Skipped, loudly, when no C compiler is present.
 */

import { execFileSync } from 'node:child_process';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { loadAdapter, planScenarioRun } from '../src/harness/adapter.js';
import { executeScenarioRun, verifyRunBundle } from '../src/harness/run-bundle.js';
import { analyzeRunCapture, compareRunVisuals } from '../src/harness/visual.js';
import { summarizeRunPerformance } from '../src/harness/performance.js';
import { decodeImage } from '../src/inspection/image.js';
import { canonicalJson } from '../src/packages/format.js';
import { GAME_DEV_ADAPTER_SCHEMA } from '../src/harness/contracts.js';

// These runs ask for hardware-performance authority on purpose: the claim
// under test is what the harness does with that authority. A hosted CI
// runner is refused it outright, which is correct and tested elsewhere, so
// the CI marker is cleared for the duration of this file only.
const savedEnvironment: Record<string, string | undefined> = {};
beforeAll(() => {
  for (const name of ['CI', 'GAME_DEV_CI_HARDWARE_ATTESTED']) {
    savedEnvironment[name] = process.env[name];
    delete process.env[name];
  }
});
afterAll(() => {
  for (const [name, value] of Object.entries(savedEnvironment)) {
    if (value === undefined) delete process.env[name];
    else process.env[name] = value;
  }
});


const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const sdkSource = path.join(repoRoot, 'probe', 'c', 'gdprobe.c');
const exampleSource = path.join(repoRoot, 'probe', 'examples', 'minimal', 'main.c');

function compilerAvailable(): boolean {
  try {
    execFileSync('cc', ['--version'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

const haveCompiler = compilerAvailable();
let root: string;
let projectRoot: string;

beforeAll(async () => {
  if (!haveCompiler) return;
  root = await fs.mkdtemp(path.join(os.tmpdir(), 'probe-sdk-'));
  projectRoot = path.join(root, 'engine');
  await fs.mkdir(path.join(projectRoot, '.game-dev'), { recursive: true });

  // The strictest flags the project claims it compiles under.
  execFileSync('cc', [
    '-std=c99', '-Wall', '-Wextra', '-Werror',
    sdkSource, exampleSource,
    '-o', path.join(projectRoot, 'engine'),
  ], { stdio: 'pipe' });

  await fs.writeFile(path.join(projectRoot, '.game-dev', 'adapter.json'), canonicalJson({
    schema: GAME_DEV_ADAPTER_SCHEMA,
    id: 'probe-example',
    name: 'Probe SDK minimal example',
    version: '1.0.0',
    scenarios: [{
      id: 'capture',
      title: 'Capture one frame',
      command: { executable: 'engine', arguments: ['{param.brightness}'], workingDirectory: '.' },
      timeoutSeconds: 30,
      capabilities: ['software-raster', 'project-write'],
      parameters: {
        brightness: { type: 'integer', required: false, default: 0, minimum: 0, maximum: 50 },
      },
      outputs: { format: 'game-dev-capture-v1', path: 'capture.json' },
    }],
  }));
});

afterAll(async () => {
  if (root) await fs.rm(root, { recursive: true, force: true });
});

async function run(brightness: number) {
  const adapter = await loadAdapter(projectRoot);
  const plan = await planScenarioRun({
    adapter,
    scenarioId: 'capture',
    runsRoot: path.join(root, 'runs'),
    parameters: { brightness },
  });
  return executeScenarioRun({ adapter, plan, confirm: true, allowGpu: false, allowPerformance: true });
}

describe.skipIf(!haveCompiler)('a bundle written by the C probe SDK', () => {
  it('is sealed and verified by the harness without any manual manifest', async () => {
    const result = await run(0);

    expect(result.manifest.status).toBe('completed');
    expect(result.manifest.evidence.captureContractValidated).toBe(true);
    // Re-verification is the proof the roster closed over what the SDK wrote.
    await expect(verifyRunBundle(result.runPath)).resolves.toBeDefined();
  }, 60_000);

  it('produces PNGs the harness decodes to the pixels the engine handed over', async () => {
    const result = await run(0);
    const analysis = await analyzeRunCapture(result.runPath);
    const color = analysis.rasters.find((raster) => raster.kind === 'color');
    const ids = analysis.rasters.find((raster) => raster.kind === 'object_id');

    expect(color).toMatchObject({ width: 16, height: 8 });
    expect(ids).toMatchObject({ width: 16, height: 8, uniqueSemanticIds: 2 });

    // Byte-level: the SDK's stored-deflate PNG decoded by pngjs must give back
    // exactly what main.c wrote. Left half (200,40,20), right half (20,40,200).
    const decoded = decodeImage(await fs.readFile(color!.path));
    expect([decoded.data[0], decoded.data[1], decoded.data[2], decoded.data[3]]).toEqual([200, 40, 20, 255]);
    const rightOffset = 15 * 4;
    expect([decoded.data[rightOffset], decoded.data[rightOffset + 1], decoded.data[rightOffset + 2]])
      .toEqual([20, 40, 200]);
  }, 60_000);

  it('slugifies a frame label the engine wrote in prose', async () => {
    const result = await run(0);
    const analysis = await analyzeRunCapture(result.runPath);

    // main.c passed "Main View". The contract requires a lowercase identifier,
    // and rejecting that after the run helps nobody.
    expect(analysis.rasters[0]?.frameLabel).toBe('main-view');
  }, 60_000);

  it('writes telemetry the harness reads, including frame indexes for warmup', async () => {
    const result = await run(0);
    const all = await summarizeRunPerformance(result.runPath);
    const trimmed = await summarizeRunPerformance(result.runPath, { warmupFrames: 1 });

    const frameTime = all.metrics.find((metric) => metric.metric === 'performance.frame_time');
    expect(frameTime?.samples).toBe(12);
    // The SDK's first sample is a deliberate 48ms cold start.
    expect(frameTime?.hitchCount).toBe(1);

    const warmed = trimmed.metrics.find((metric) => metric.metric === 'performance.frame_time');
    // Two, not one: the frame-0 telemetry sample AND the frame-0 draw_calls
    // measurement both belong to the cold-start frame. Warmup applies across
    // sources, which is the behaviour a caller wants and worth pinning.
    expect(trimmed.warmupSamplesExcluded).toBe(2);
    expect(warmed?.samples).toBe(11);
    expect(warmed?.hitchCount).toBe(0);
  }, 60_000);

  it('cannot mint GPU authority from a software renderer, at either layer', async () => {
    const result = await run(0);
    const { evidence } = result.manifest;

    // main.c tried gdprobe_attest_gpu on a software renderer and the SDK
    // refused it. The harness independently downgrades. Both must agree.
    expect(evidence.rendererClass).toBe('software');
    expect(evidence.softwareRasterizedLane).toBe(true);
    expect(evidence.adapterReportedGpuExecution).toBe(false);
    expect(evidence.hardwarePerformanceEvidenceAdmitted).toBe(false);
    // Nothing to refuse at the harness, because the SDK already refused it
    // at source -- and recorded why in the notes.
    expect(evidence.refusedAdapterClaims).toEqual([]);
  }, 60_000);

  it('produces two runs the semantic diff can compare object by object', async () => {
    const baseline = await run(0);
    const candidate = await run(40);
    const comparison = await compareRunVisuals({
      baselineRunPath: baseline.runPath,
      candidateRunPath: candidate.runPath,
      threshold: 0,
      outputPath: path.join(root, 'diff'),
    });
    const color = comparison.pairs.find((pair) => pair.kind === 'color');

    // Only the left object's red channel moved, by exactly the brightness arg.
    expect(color?.comparable).toBe(true);
    const left = color?.semanticRegions?.find((region) => region.objectId === '0x000001');
    const right = color?.semanticRegions?.find((region) => region.objectId === '0x000002');
    expect(left?.changedPixelRatio).toBe(1);
    expect(right?.changedPixelRatio).toBe(0);
    expect(comparison.verdict).toBe('changed');
    expect(comparison.summary.join(' ')).toContain('0x000001');
  }, 60_000);
});

describe.skipIf(haveCompiler)('probe SDK without a C compiler', () => {
  it('reports that it was skipped rather than silently passing', () => {
    // A skip that looks like a pass is how a broken SDK ships. This exists so
    // the reporter shows the skip by name.
    expect(haveCompiler).toBe(false);
  });
});
