/**
 * Job persistence.
 *
 * One JSON file per job, written atomically (temp file + fsync + rename) so a
 * crash mid-write can never leave a half-parsed job behind — the old file
 * either survives intact or is replaced whole.
 *
 * Chosen over SQLite deliberately: Node's built-in `node:sqlite` is still
 * experimental and needs Node >= 22.5, and a native driver would force every
 * installer of this CLI through a build toolchain. At the scale this harness
 * operates (hundreds of jobs, single writer) a keyed file store is sufficient,
 * and it keeps `game-dev` working everywhere. Reasoning recorded in
 * docs/architecture.md.
 */

import { randomBytes } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { AssetJob } from '../domain/asset-job.js';
import { assetJobSchema } from './asset-job-schema.js';
import { AssetPipelineError, notFound } from '../util/errors.js';

const JOB_FILE_SUFFIX = '.json';

export class JobStore {
  private constructor(private readonly dir: string) {}

  static async open(dir: string): Promise<JobStore> {
    await fs.mkdir(dir, { recursive: true });
    return new JobStore(dir);
  }

  private fileFor(id: string): string {
    // Job ids are generated by us (`asset_<uuid>`), but this store is also the
    // boundary where a caller-supplied id would land, so refuse anything that
    // could escape the directory rather than trusting the caller.
    if (!/^asset_[A-Za-z0-9-]{1,64}$/.test(id)) {
      throw new AssetPipelineError('INVALID_INPUT', `malformed asset job id: ${id}`, {
        details: { id },
      });
    }
    return path.join(this.dir, `${id}${JOB_FILE_SUFFIX}`);
  }

  async save(job: AssetJob): Promise<void> {
    const target = this.fileFor(job.id);
    this.validate(job, job.id);
    const tmp = `${target}.tmp-${randomBytes(8).toString('hex')}`;
    const payload = `${JSON.stringify(job, null, 2)}\n`;

    try {
      const handle = await fs.open(tmp, 'wx');
      try {
        await handle.writeFile(payload, 'utf8');
        // fsync before rename: rename is atomic, but without the flush the
        // renamed file can still be empty after a power loss.
        await handle.sync();
      } finally {
        await handle.close();
      }
      await fs.rename(tmp, target);
    } catch (err) {
      // Clean up on every failure path so a full disk does not leak temp files.
      await fs.rm(tmp, { force: true });
      throw err;
    }

    // Also fsync the DIRECTORY: the file's bytes are durable after the sync
    // above, but the new directory entry is not. Losing that entry on a job we
    // just created means credits were spent with no record that survives —
    // exactly the case findByProviderTaskId exists to recover.
    try {
      const dirHandle = await fs.open(this.dir, 'r');
      try {
        await dirHandle.sync();
      } finally {
        await dirHandle.close();
      }
    } catch {
      // Directory fsync is unsupported on some platforms and filesystems.
      // The data write already succeeded, so this is a durability nicety, not
      // a reason to fail a save that otherwise worked.
    }
  }

  /**
   * Validate what came off disk before trusting it.
   *
   * A bare `as AssetJob` cast lets a record written by a future version load
   * with missing arrays, and the first `.length` access then throws somewhere
   * far away from the actual cause.
   */
  private validate(parsed: unknown, id: string): AssetJob {
    const result = assetJobSchema.safeParse(parsed);
    if (!result.success) {
      throw new AssetPipelineError('INVALID_STATE', `job ${id} is corrupt or has an unsupported schemaVersion`, {
        details: { id, issues: result.error.issues },
      });
    }
    if (result.data.id !== id) throw new AssetPipelineError('INVALID_STATE', `job ${id} has a mismatched identity`, { details: { id, storedId: result.data.id } });
    // Validation must not rewrite provenance through defaults or transformations.
    return parsed as AssetJob;
  }

  async get(id: string): Promise<AssetJob> {
    const job = await this.find(id);
    if (!job) throw notFound('asset job', id);
    return job;
  }

  async find(id: string): Promise<AssetJob | undefined> {
    let raw: string;
    try {
      raw = await fs.readFile(this.fileFor(id), 'utf8');
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
      throw err;
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (err) {
      throw new AssetPipelineError('INVALID_STATE', `job ${id} is corrupt on disk`, { cause: err });
    }
    return this.validate(parsed, id);
  }

  async list(): Promise<AssetJob[]> {
    this.corrupt = [];
    let entries: string[];
    try {
      entries = await fs.readdir(this.dir);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return [];
      throw err;
    }

    const jobs: AssetJob[] = [];
    for (const entry of entries) {
      if (!entry.endsWith(JOB_FILE_SUFFIX)) continue;
      // The workspace ledger shares this directory but is not an asset job.
      if (entry === 'spend-ledger.json') continue;
      if (entry.includes('.tmp-')) continue;

      let raw: string;
      try {
        raw = await fs.readFile(path.join(this.dir, entry), 'utf8');
      } catch (err) {
        const code = (err as NodeJS.ErrnoException).code;
        // A file that vanished between readdir and readFile is benign. Anything
        // else — EACCES, EISDIR, EMFILE — must NOT be swallowed: silently
        // dropping a job makes an in-flight PAID task look like it never
        // existed, and the caller may re-submit and pay twice.
        if (code === 'ENOENT') continue;
        throw err;
      }

      try {
        jobs.push(this.validate(JSON.parse(raw), entry.slice(0, -JOB_FILE_SUFFIX.length)));
      } catch (err) {
        // A corrupt or future-schema record is skipped rather than throwing,
        // so one bad file cannot hide every good one — but it is surfaced.
        this.corrupt.push({ file: entry, reason: err instanceof Error ? err.message : String(err) });
      }
    }
    jobs.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
    return jobs;
  }

  /** Records skipped during the most recent `list()`, so callers can report them. */
  private corrupt: { file: string; reason: string }[] = [];

  lastListingSkipped(): readonly { file: string; reason: string }[] {
    return this.corrupt;
  }

  /** Map a provider's task id back to our job. Provider ids are metadata, not identity. */
  async findByProviderTaskId(taskId: string): Promise<AssetJob | undefined> {
    const jobs = await this.list();
    const matches = jobs.filter((job) => job.model3d?.providerTaskId === taskId);
    if (matches.length > 1) throw new AssetPipelineError('INVALID_STATE', 'Multiple asset jobs claim the same provider task; inspect the evidence before recovery', { details: { taskId, assetJobIds: matches.map((job) => job.id) } });
    if (!matches.length && this.corrupt.length) throw new AssetPipelineError('INVALID_STATE', 'Provider task lookup is incomplete because asset jobs are corrupt; do not resubmit based on a missing result', { details: { taskId, corrupt: this.corrupt } });
    return matches[0];
  }

  async delete(id: string): Promise<void> {
    await fs.rm(this.fileFor(id), { force: true });
  }
}
